# 数组的创建和访问

In [1]:
import numpy as np

In [2]:
# create from python list
list_1 = [1, 2, 3, 4]

In [3]:
list_1

[1, 2, 3, 4]

In [9]:
array_1 = np.array(list_1)

In [10]:
array_1

array([1, 2, 3, 4])

In [11]:
list_2 = [5, 6, 7, 8]

In [14]:
array_2 = np.array([list_1,list_2])

In [15]:
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
array_2.shape

(2, 4)

In [17]:
array_2.size

8

In [18]:
array_2.dtype

dtype('int32')

In [19]:
array_3 = np.array([[1.0,2,3],[4.0,5,6]])

In [20]:
array_3.dtype

dtype('float64')

In [23]:
array_4 = np.arange(1, 10, 2)

In [24]:
array_4

array([1, 3, 5, 7, 9])

In [25]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.eye(5).dtype

dtype('float64')

In [29]:
a = np.arange(1,10)

In [30]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a[1]

2

In [32]:
a[1:5]

array([2, 3, 4, 5])

In [33]:
b = np.array([[1,2,3],[4,5,6]])

In [34]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
b[1][0]

4

In [36]:
b[1,0]

4

In [37]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [38]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
c[:2,1:]

array([[2, 3],
       [5, 6]])