# 使用pickle序列化numpy array

In [1]:
import pickle
import numpy as np

In [2]:
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
f = open('x.pk1','wb')

In [5]:
pickle.dump(x, f)

In [7]:
!dir

 驱动器 C 中的卷是 Win
 卷的序列号是 CE44-B535

 C:\Users\matingting 的目录

2022/02/15  16:34    <DIR>          .
2022/02/15  16:34    <DIR>          ..
2022/02/15  13:57    <DIR>          .android
2022/02/15  10:24            28,494 .bash_history
2021/12/30  10:04    <DIR>          .bifrost
2022/02/15  13:57    <DIR>          .BigNox
2021/08/20  14:10    <DIR>          .config
2021/09/28  21:09               190 .gitconfig
2022/02/15  16:33    <DIR>          .ipynb_checkpoints
2022/02/15  14:26    <DIR>          .ipython
2022/01/24  13:16    <DIR>          .jupyter
2022/02/15  10:16               104 .lesshst
2021/08/24  16:57    <DIR>          .umi3
2021/08/20  13:29    <DIR>          .vscode
2021/08/24  16:31               121 .yarnrc
2021/08/17  10:20    <DIR>          3D Objects
2021/09/27  16:54         8,294,826 app_download_native_report202108.sql
2022/02/15  15:58             9,468 Array.ipynb
2022/02/15  16:34             1,580 Array的input和output.ipynb
2021/08/17  10:20    <DIR>          Co

In [8]:
f = open('x.pk1','rb')

In [9]:
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.save('one_array', x)

In [11]:
!dir

 驱动器 C 中的卷是 Win
 卷的序列号是 CE44-B535

 C:\Users\matingting 的目录

2022/02/15  16:36    <DIR>          .
2022/02/15  16:36    <DIR>          ..
2022/02/15  13:57    <DIR>          .android
2022/02/15  10:24            28,494 .bash_history
2021/12/30  10:04    <DIR>          .bifrost
2022/02/15  13:57    <DIR>          .BigNox
2021/08/20  14:10    <DIR>          .config
2021/09/28  21:09               190 .gitconfig
2022/02/15  16:33    <DIR>          .ipynb_checkpoints
2022/02/15  14:26    <DIR>          .ipython
2022/01/24  13:16    <DIR>          .jupyter
2022/02/15  10:16               104 .lesshst
2021/08/24  16:57    <DIR>          .umi3
2021/08/20  13:29    <DIR>          .vscode
2021/08/24  16:31               121 .yarnrc
2021/08/17  10:20    <DIR>          3D Objects
2021/09/27  16:54         8,294,826 app_download_native_report202108.sql
2022/02/15  15:58             9,468 Array.ipynb
2022/02/15  16:36             5,386 Array的input和output.ipynb
2021/08/17  10:20    <DIR>          Co

In [12]:
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
y = np.arange(20)

In [14]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
np.savez('two_array.npz', a=x, b=y)

In [16]:
!dir

 驱动器 C 中的卷是 Win
 卷的序列号是 CE44-B535

 C:\Users\matingting 的目录

2022/02/15  16:37    <DIR>          .
2022/02/15  16:37    <DIR>          ..
2022/02/15  13:57    <DIR>          .android
2022/02/15  10:24            28,494 .bash_history
2021/12/30  10:04    <DIR>          .bifrost
2022/02/15  13:57    <DIR>          .BigNox
2021/08/20  14:10    <DIR>          .config
2021/09/28  21:09               190 .gitconfig
2022/02/15  16:33    <DIR>          .ipynb_checkpoints
2022/02/15  14:26    <DIR>          .ipython
2022/01/24  13:16    <DIR>          .jupyter
2022/02/15  10:16               104 .lesshst
2021/08/24  16:57    <DIR>          .umi3
2021/08/20  13:29    <DIR>          .vscode
2021/08/24  16:31               121 .yarnrc
2021/08/17  10:20    <DIR>          3D Objects
2021/09/27  16:54         8,294,826 app_download_native_report202108.sql
2022/02/15  15:58             9,468 Array.ipynb
2022/02/15  16:36             5,386 Array的input和output.ipynb
2021/08/17  10:20    <DIR>          Co

In [17]:
np.load('two_array.npz')

In [18]:
c = np.load('two_array.npz')

In [19]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])